services:
  flask-app:
    build: .
    restart: always
    ports:
      - 8080:8000
    command: >
      ash -c "export FLASK_SECRET_KEY=$(openssl rand -base64 32) &&
              export CSRF_SECRET=$(openssl rand -base64 32) &&
              gunicorn --conf gunicorn_conf.py -b 0.0.0.0:8000 app:app"
