services:
  flask-app:
    build: .
    restart: always
    ports:
      - "${PORT?Variable PORT not set}:8000"
    command: >
      ash -c "export FLASK_SECRET_KEY=$(openssl rand -base64 32) &&
              export CSRF_SECRET=$(openssl rand -base64 32) &&
              gunicorn --conf gunicorn_conf.py -b 0.0.0.0:8000 app:app"
  nginx:
    build: nginx
    restart: always
    environment: 
    - FLASK_SERVER_ADDR=flask-app:8000
    ports:
      - 8080:80
    depends_on:
      - flask-app
    command: /app/start.sh
