name: run-test-artifact
description: "Download the built test docker image and run it"

inputs:
   repo-read-token:
     required: true
     description: "A GitHub PAT with actions:read permission on this repo."

runs:
  using: "composite"
  steps:
  - name: Retrieve Docker image
    uses: actions/download-artifact@v4
    with:
      name: test-build-${{ github.sha }}
      run-id: ${{ github.event.workflow_run.id }}
      github-token: ${{ inputs.repo-read-token }}
  - name: Docker test run
    shell: bash
    run: |
      docker load < test_image.tar
      PORT=8000
      docker run -td -p 8080:${PORT} --name test -e FLASK_LOG_LEVEL=DEBUG -e PORT=${PORT} -e COVERAGE_FILE=/home/nonroot/.cov --rm test:latest
