name: coverage
# NB: this will run even if docker-test-build fails

on:
  workflow_run:
    workflows:
      - docker-test-build
    types:
      - completed

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Deploy frontend
      uses: ./.github/actions/run-test-artifact
      with:
        repo-read-token: ${{ secrets.GH_PAT }}
    - name: Coverage error check
      run: docker exec test python -m pytest --cov tests -p no:cacheprovider
    - name: Coverage percentage check
      run: |
        target_coverage_pc=90
        coverage_pc=$(docker exec test python -m pytest --cov tests -p no:cacheprovider | awk '$1 == "TOTAL" {print $NF+0}')
        exit $(( coverage_pc < target_coverage_pc ))
