name: docker-hub-push

on:
  workflow_run:
    workflows:
      - release-test
    types:
      - completed

jobs:
  push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download and run docker image
      uses: ./.github/actions/download-docker-artifact
      with:
        repo-read-token: ${{ secrets.GH_PAT }}
        build-type: 'release'
    - name: Push to docker hub
      run: |
        docker tag release:latest emit5/vat-invoice:${{ github.sha }}
        docker push emit5/vat-invoice:${{ github.sha }}
