name: docker-hub-push

on:
  workflow_run:
    workflows:
      - release-test
    types:
      - completed

jobs:
  push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Wait for all workflows to pass
      run: |
        GITHUB_SHA=${{ github.sha }}
        REPO_PATH=${{ github.repository }}
        echo REPO_PATH = $REPO_PATH
        GH_TOKEN=${{ secrets.GH_PAT }}
        pip install -r requirements_test.txt
        python tests/wait_for_workflow_completion.py ${{ github.workflow }}
    - name: Download docker image artifact
      uses: ./.github/actions/download-docker-artifact
      with:
        repo-read-token: ${{ secrets.GH_PAT }}
        build-type: 'release'
    - name: Push to docker hub
      run: |
        docker tag release:latest emit5/vat-invoice:${{ github.sha }}
        docker push emit5/vat-invoice:${{ github.sha }}
