name: flake8
# NB: this will run even if docker-test-build fails

on:
  workflow_run:
    workflows:
      - docker-test-build
    types:
      - completed

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Deploy frontend
      uses: ./.github/actions/run-test-artifact
      with:
        repo-read-token: ${{ secrets.GH_PAT }}
    - name: flake8
      run: docker exec test python -m flake8 --ignore=D107,E501,W503 --exclude=tests/*
