name: mypy
# NB: this will run even if docker-test-build fails

on:
  workflow_run:
    workflows:
      - docker-test-build
    types:
      - completed

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy frontend
        uses: ./.github/actions/run-test-artifact
        with:
          repo-read-token: ${{ secrets.GH_PAT }}
      - name: mypy
        run: docker exec test python -m mypy . --exclude '/tests/'
