name: pycodestyle
# NB: this will run even if docker-test-build fails

on:
  workflow_run:
    workflows:
      - docker-test-build
    types:
      - completed

jobs:
  pycodestyle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download and run docker image
      uses: ./.github/actions/download-docker-artifact
      with:
        repo-read-token: ${{ secrets.GH_PAT }}
    - name: pycodestyle
      run: docker exec test sh -c 'python -m pycodestyle *.py --exclude=tests/*'
    - name: Save result
      uses: ./.github/actions/save-workflow-result
      with:
        result: '0'
