name: pydocstyle
# NB: this will run even if docker-test-build fails

on:
  workflow_run:
    workflows:
      - docker-test-build
    types:
      - completed

jobs:
  pydocstyle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Deploy frontend
      uses: ./.github/actions/run-test-artifact
      with:
        repo-read-token: ${{ secrets.GH_PAT }}
    - name: pydocstyle
      run: docker exec test python -m pydocstyle $(find . -path . -prune -o -name '*.py' -print) --ignore=D107,D203,D213
