name: release-test

on:
  workflow_run:
    workflows:
      - docker-release-build
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Wait for and download docker image artifact
      uses: ./.github/actions/download-docker-artifact
      with:
        repo-read-token: ${{ secrets.GH_PAT }}
        build-type: 'release'
    - name: Release test
      run: |
        PORT=8000
        FLASK_SECRET_KEY=$(openssl rand -base64 32)
        CSRF_SECRET=$(openssl rand -base64 32)
        docker run -d -p 8080:${PORT} --name release -e PORT=${PORT} \
        -e FLASK_SECRET_KEY=${FLASK_SECRET_KEY} \
        -e CSRF_SECRET=${CSRF_SECRET} \
        --rm release:latest
        sleep 4
        page=$(curl http://127.0.0.1:8080)
        if ! grep -q "VAT invoice generator" <<< "$page"; then echo "Page GET failed." && exit 1; fi
        json_data=$(curl http://127.0.0.1:8080/version)
        echo JSON data = $json_data
        hash=$(echo $json_data | python3 -c "import sys, json; print(json.load(sys.stdin)['commit_hash'])")
        echo Hash = $hash
        echo GSHA = ${{ github.sha }}
        if [ "$hash" != "${{ github.sha }}" ]; then echo "Commit hash incorrect." && exit 1; fi
    - name: Save result
      if: always()
      uses: ./.github/actions/save-workflow-result
      with:
        result: ${{ job.status }}
