name: release-test

on:
  workflow_run:
    workflows:
      - docker-release-build
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Wait for docker image artifact
      run: |
        export GITHUB_SHA=${{ github.sha }}
        export REPO_PATH=${{ github.repository }}
        export GH_TOKEN=${{ secrets.GH_PAT }}
        pip install -r requirements_test.txt
        python .github/wait_for_workflow_artifacts.py - release-build-${{ github.sha }}
    - name: Download docker image artifact
      uses: ./.github/actions/download-docker-artifact
      with:
        repo-read-token: ${{ secrets.GH_PAT }}
        build-type: 'release'
    - name: Release test
      run: |
        PORT=8000
        docker run -d -p 8080:${PORT} --name release -e PORT=${PORT} --rm release:latest
        sleep 4
        page=$(curl http://127.0.0.1:8080)
        if ! grep -q "VAT invoice generator" <<< "$page"; then echo "Page GET failed." && exit 1; fi
        json_data=$(curl http://127.0.0.1:8080/version)
        echo JSON data = $json_data
        hash=$(echo $json_data | python3 -c "import sys, json; print(json.load(sys.stdin)['commit_hash'])")
        echo Hash = $hash
        echo GSHA = ${{ github.sha }}
        if [ "$hash" != "${{ github.sha }}" ]; then echo "Commit hash incorrect." && exit 1; fi
    - name: Save result
      if: always()
      uses: ./.github/actions/save-workflow-result
      with:
        result: ${{ job.status }}
