name: tag-check

on:
  workflow_run:
    workflows:
      - docker-release-build
    types:
      - completed

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      actions: 'write'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Wait for docker image artifact
      run: |
        export GITHUB_SHA=${{ github.sha }}
        export REPO_PATH=${{ github.repository }}
        export GH_TOKEN=${{ secrets.GH_PAT }}
        pip install -r requirements_test.txt
        python .github/wait_for_workflow_artifacts.py - release-build-${{ github.sha }}
    - name: Download docker image artifact
      uses: ./.github/actions/download-docker-artifact
      with:
          repo-read-token: ${{ secrets.GH_PAT }}
          build-type: 'release'
    - name: Check for commit tag
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        PORT=8000
        docker run -d -p 8080:${PORT} --name release -e PORT=${PORT} --rm release:latest
        sleep 4
        json_data=$(curl http://127.0.0.1:8080/version)
        git_tag=$(echo $json_data | python3 -c "import sys, json; print(json.load(sys.stdin)['version'])")
        echo Tag = $git_tag
        if [[ $git_tag != v* ]]
        then
          echo "Commit was not version tagged: cancel push/deploy."
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}
        else
          echo "Proceeding with DockerHub push and cloud deployment."
        fi
    - name: Re-save image for chained workflow_run
      uses: actions/upload-artifact@v4
      with:
        name: release-build-${{ github.sha }}
        path: release_image.tar
        if-no-files-found: error
        retention-days: 1
