name: tests
# NB: this will run even if docker-test-build fails

on:
  workflow_run:
    workflows:
      - docker-test-build
    types:
      - completed

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download and run docker image
      uses: ./.github/actions/download-docker-artifact
      with:
        repo-read-token: ${{ secrets.GH_PAT }}
    - name: Tests
      id: run
      run: docker exec test python -m pytest -p no:cacheprovider
    - name: Save result
      if: always()
      uses: ./.github/actions/save-workflow-result
      with:
        result: ${{ job.status }}
